name: administrative_panel_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  url_strategy: ^0.2.0
  get: ^4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.4
  dotenv: ^4.1.0
  intl: ^0.18.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - web/assets/images/
    - web/assets/icons/
    - .env
